#!/bin/bash

__os=$(uname -s)
lang=$(basename $SHELL)

declare -A __clipboard_cmds=(
	[Darwin_copy]=pbcopy
	[Darwin_paste]=pbpaste
	[Linux_copy]="xsel -ib"
	[Linux_paste]="xsel -ob"
)

__clipboard_copy=${__clipboard_cmds[${__os}_copy]}
__clipboard_paste=${__clipboard_cmds[${__os}_paste]}

__src_files() {
	local files=(
		functs
		aliases
		dfuncts
		programs
	)

	for f in "${files[@]}"; do
		[ -f "${TIGH_CONFIG}/${f}" ] && source ${TIGH_CONFIG}/$f
	done

	[ ! -d ${TIGH_CONFIG}-secret ] && return

	for f in ${TIGH_CONFIG}-secret/*; do
		[ -f "$f" ] && source $f
	done
}

__src_files
