#!/bin/bash

__os=$(uname -s)
lang=$(basename $SHELL)

declare -A __clipboard_cmds=(
	[Darwin_copy]=pbcopy
	[Darwin_paste]=pbpaste
	[Linux_copy]="xsel"
	[Linux_paste]="xsel"
)

declare -A __clipboard_args=(
	[Darwin_copy]=
	[Darwin_paste]=
	[Linux_copy]="-ib"
	[Linux_paste]="-ob"
)

__clipboard_copy=${__clipboard_cmds[${__os}_copy]}
__clipboard_paste=${__clipboard_cmds[${__os}_paste]}

__clipboard_copy_args=${__clipboard_args[${__os}_copy]}
__clipboard_paste_args=${__clipboard_args[${__os}_paste]}

unset __clipboard_cmds
unset __clipboard_args

__src_files() {
	local files=(
		functs
		envars
		aliases
		dfuncts
		programs
	)

	for f in "${files[@]}"; do
		[ -f "${TIGH_CONFIG}/${f}" ] && source ${TIGH_CONFIG}/$f
	done

	[ ! -d ${TIGH_CONFIG}-secret ] && return

	for f in ${TIGH_CONFIG}-secret/*; do
		[ -f "$f" ] && source $f
	done
}

__src_files
