#!/bin/bash

__src_programs() {
	local programs=(
		/usr/share/z/z.sh
		/opt/homebrew/etc/profile.d/z.sh
	)

	for p in "${programs[@]}"; do
		[ -r "$p" ] || {
			local base=$(basename $p)
			[ ! -f "${HOME}/.${base}.suppress" ] && echo "$p not installed."
			continue
		}

		[ -r "$p" ] && source $p
	done
}

__src_programs
