local palette = require "tigh-latte.theme.palette"
return {
	CmpItemAbbrMatch = { fg = palette.white },
	CmpItemAbbrMatchFuzzy = { fg = palette.white },
	CmpItemKindFunction = { fg = palette.cyan },
	CmpItemKindConstant = { fg = palette.purple },
	CmpItemKindKey = { fg = palette.purple },

	CmpItemKindObject = { fg = palette.fg },

	CmpItemAbbr = { fg = palette.fg },
	CmpItemAbbrDeprecated = { fg = palette.light_grey, strikethrough = true },
	CmpItemMenu = { fg = palette.light_grey },
	CmpItemKind = { fg = palette.purple }, --fmt = cfg.cmp_itemkind_reverse and "reverse" },


	CmpItemKindDefault = { fg = palette.purple },
	CmpItemKindArray = { fg = palette.yellow },
	CmpItemKindBoolean = { fg = palette.orange },
	CmpItemKindClass = { fg = palette.yellow },
	CmpItemKindColor = { fg = palette.green },
	CmpItemKindConstructor = { fg = palette.blue },
	CmpItemKindEnum = { fg = palette.purple },
	CmpItemKindEnumMember = { fg = palette.yellow },
	CmpItemKindEvent = { fg = palette.yellow },
	CmpItemKindField = { fg = palette.purple },
	CmpItemKindFile = { fg = palette.blue },
	CmpItemKindFolder = { fg = palette.orange },
	CmpItemKindInterface = { fg = palette.green },
	CmpItemKindKeyword = { fg = palette.yellow },
	CmpItemKindMethod = { fg = palette.blue },
	CmpItemKindModule = { fg = palette.orange },
	CmpItemKindNamespace = { fg = palette.red },
	CmpItemKindNull = { fg = palette.grey },
	CmpItemKindNumber = { fg = palette.orange },
	CmpItemKindOperator = { fg = palette.red },
	CmpItemKindPackage = { fg = palette.yellow },
	CmpItemKindProperty = { fg = palette.cyan },
	CmpItemKindReference = { fg = palette.orange },
	CmpItemKindSnippet = { fg = palette.red },
	CmpItemKindString = { fg = palette.green },
	CmpItemKindStruct = { fg = palette.purple },
	CmpItemKindText = { fg = palette.light_grey },
	CmpItemKindTypeParameter = { fg = palette.red },
	CmpItemKindUnit = { fg = palette.green },
	CmpItemKindValue = { fg = palette.orange },
	CmpItemKindVariable = { fg = palette.purple },
}
