local palette = require "tigh-latte.theme.palette"
return {
	Normal = { fg = palette.fg, bg = "none" },        -- Background
	NormalFloat = { fg = palette.fg, bg = palette.bg1 }, -- Floating Window Background
	Visual = { bg = palette.bg3 },
	VisualNOS = { fg = "none", bg = palette.bg2, underline = true },
	FloatBorder = { fg = palette.grey, bg = palette.bg1 },

	CurSearch = { fg = palette.bg0, bg = palette.light_grey },
	IncSearch = { fg = palette.bg0, bg = palette.light_grey },
	Comment = { fg = palette.grey },

	Search = { fg = palette.bg0, bg = palette.muted_white },

	Terminal = { fg = palette.fg, bg = "none" },
	EndOfBuffer = { fg = palette.bg0, bg = "none" },
	FoldColumn = { fg = palette.fg, bg = "none" },
	Folded = { fg = palette.fg, bg = "none" },
	SignColumn = { fg = palette.fg, bg = "none" },
	ToolbarLine = { fg = palette.fg },
	Cursor = { reverse = true },
	vCursor = { reverse = true },
	iCursor = { reverse = true },
	lCursor = { reverse = true },
	CursorIM = { reverse = true },
	CursorColumn = { bg = palette.bg1 },
	CursorLine = { bg = palette.bg1 },
	ColorColumn = { bg = palette.bg1 },
	CursorLineNr = { fg = palette.fg },
	LineNr = { fg = palette.grey },
	Conceal = { fg = palette.grey, bg = palette.bg1 },
	Added = { fg = palette.green },
	Removed = { fg = palette.red },
	Changed = { fg = palette.blue },
	DiffAdd = { fg = palette.none, bg = palette.diff_add },
	DiffChange = { fg = palette.none, bg = palette.diff_change },
	DiffDelete = { fg = palette.none, bg = palette.diff_delete },
	DiffText = { fg = palette.none, bg = palette.diff_text },
	DiffAdded = { fg = palette.green },
	DiffChanged = { fg = palette.blue },
	DiffRemoved = { fg = palette.red },
	DiffDeleted = { fg = palette.red },
	DiffFile = { fg = palette.cyan },
	DiffIndexLine = { fg = palette.grey },
	Directory = { fg = palette.cyan },
	ErrorMsg = { fg = palette.red, bold = true },
	WarningMsg = { fg = palette.yellow, bold = true },
	MoreMsg = { fg = palette.blue, bold = true },
	Substitute = { fg = palette.bg0, bg = palette.green },
	MatchParen = { fg = palette.none, bg = palette.grey },
	NonText = { fg = palette.grey },
	Whitespace = { fg = palette.grey },
	Special = { fg = palette.cyan },
	SpecialChar = { fg = palette.cyan },
	SpecialKey = { fg = palette.grey },
	Structure = { fg = palette.fg },
	Typedef = { fg = palette.fg },
	Function = { fg = palette.fg },
	ArielObject = { fg = palette.fg },
	Pmenu = { fg = palette.fg, bg = palette.bg1 },
	PmenuSbar = { fg = palette.none, bg = palette.bg1 },
	PmenuSel = { fg = palette.bg0, bg = palette.bg_blue },
	WildMenu = { fg = palette.bg0, bg = palette.blue },
	PmenuThumb = { fg = palette.none, bg = palette.grey },
	Question = { fg = palette.yellow },
	SpellBad = { fg = palette.none, undercurl = true, sp = palette.red },
	SpellCap = { fg = palette.none, undercurl = true, sp = palette.yellow },
	SpellLocal = { fg = palette.none, undercurl = true, sp = palette.blue },
	SpellRare = { fg = palette.none, undercurl = true, sp = palette.purple },
	StatusLine = { fg = palette.fg, bg = palette.bg2 },
	StatusLineTerm = { fg = palette.fg, bg = palette.bg2 },
	StatusLineNC = { fg = palette.grey, bg = palette.bg1 },
	StatusLineTermNC = { fg = palette.grey, bg = palette.bg1 },
	TabLine = { fg = palette.fg, bg = palette.bg1 },
	TabLineFill = { fg = palette.grey, bg = palette.bg1 },
	TabLineSel = { fg = palette.bg0, bg = palette.fg },
	WinSeparator = { fg = palette.bg3 },
	QuickFixLine = { fg = palette.blue, underline = true },
	Debug = { fg = palette.yellow },
	debugPC = { fg = palette.bg0, bg = palette.green },
	debugBreakpoint = { fg = palette.bg0, bg = palette.red },
	ToolbarButton = { fg = palette.bg0, bg = palette.bg_blue },
}
