#!/bin/bash

export EDITOR=nvim
export PSQL_EDITOR=nvim

export PATH="${HOME}/go/bin:${HOME}/.cargo/bin:${HOME}/.local/bin:$PATH"

export HISTFILE=${HOME}/.zsh_history
export HISTSIZE=999999999
export SAVEHIST=999999999

export FZF_DEFAULT_OPTS='
	--reverse
	--height=50%
	--color=fg+:#abb2bf
	--color=hl+:#d7af87
	--color=hl:#d7af87
	--color=info:#5c6370
	--color=prompt:#af5f5a
	--color=pointer:#af5f5a'

export STARSHIP_CONFIG=~/.config/starship/starship.toml

setopt INC_APPEND_HISTORY
