#!/bin/bash

__wezterm_set() {
	key="$1"
	val="$2"

	[ -z "$key" ] && return

	val=$(printf $val | base64)

	osc="\033]1337;SetUserVar=${key}=${val}\007"

	[ -n "$TMUX" ] && osc="\033Ptmux;\033${osc}\033\\"

	# Redirect to stderr because git over ssh is wile.
	printf "$osc" 1>&2
}

nvm() {
	source ~/.nvm/nvm.sh || echo "not installed" && return
	source ~/.nvm/bash_completion
	nvm $@
}

f() {
	local root=$@

	[ -z "$root" ] && {
		local root=(
			~/Dev/github.com
			~/Dev/git.tigh.io
		)
	} || {
		local root=()
		for var in "$@"; do root+=$var done

	}

	printf "\033[1A\033[2K"

	local result=$(fd \
			--hidden \
			--full-path \
			--max-depth 2 \
			--color=never \
			--exclude vendor \
			--exclude=.git \
			--exclude=node_modules \
			--exclude cdk.out \
			--exclude node_modules \
			--exclude dist \
			--exclude build \
			--exclude __pycache__ \
			--exclude .venv \
			--type d . ${root} | fzf)

	printf "\033[1A\033[2K\033[1A\033[2K"

	[ ! -z "$result" ] && cd $result
}

z() {
	eval "$(zoxide init zsh)"
	z $@
}

mkcd() {
	[ -z "$1" ] && echo WAT && return
	mkdir -p $1 && cd $1
}

vman() {
	[ -z "$1" ] && echo "Ní thig liom leathanach treorach a thaispeáint ar faic." && return
	man $1 | vim -
}

rmi() {
	[ -z "$1" ] && echo "Iarr faic orm, faigh faic uaim." && return

	local image_text=$1
	docker rmi -f $(docker images | grep $image_text | awk '{print $1, $2}' | tr ' ' ':')
}

try() {
	while ! $@; do
		sleep 0.5
	done
}

m() {
	watch -n 1 "$@"
}

make() {
	local makefile=Makefile.mine

	if ! /usr/bin/make -f $makefile -n $@ &>/dev/null; then
		makefile=Makefile
	fi

	/usr/bin/make -f $makefile $@
}

goinit() {
	local mod=$(basename $(pwd))

	go mod init github.com/tigh-latte/$mod
}

gitp() {(
	local git_repo=".git"

	until [ -d $git_repo ] || [ -f $git_repo ] || [ "$PWD" = "/" ]; do
		pushd $(pwd -P)/.. &> /dev/null
	done
	[ "$PWD" = "/" ] && return 1

	if [ -d $git_repo ]; then
		local git_head=$git_repo/HEAD
	elif [ -f $git_repo ]; then
		local git_head=$(cut -d\  -f2 $git_repo)/HEAD
	fi

	local branch_name=$(sed 's#^ref: refs/heads/##' $git_head)

	printf "git push origin ${branch_name}:${branch_name}" | \
		${__clipboard_copy} ${__clipboard_copy_args} && ${__clipboard_paste} ${__clipboard_paste_args}
)}

gitpr() {(
	local git_folder=".git"
	local target_branch="master"
	[ -f "${git_folder}/refs/remotes/origin/main" ] && target_branch=main

	until [ -d $git_folder ] || [ "$PWD" = "/" ]; do
		pushd $(pwd -P)/.. &> /dev/null
	done
	[ -d $git_folder ] || exit 1

	local branch_name=$(sed 's#^ref: refs/heads/##' $git_folder/HEAD)
	local reponame=$(basename $PWD)
	[ -f "${git_folder}/refs/remotes/origin/$1" ] && target_branch=$1

	## TODO: Get this info from .git to make portable across git hosts.
	printf "https://github.com/tigh-latte/$reponame/compare/${target_branch}...${branch_name}" | ${__clipboard_copy}

	open https://github.com/tigh-latte/$reponame/compare/${target_branch}...${branch_name}
)}

stats() {
	history | awk '{CMD[$2]++;count++;}END { for (a in CMD)print CMD[a] " "  CMD[a]/count*100 "% " a;}' | grep -v './' | column -c3 -s ' ' -t | sort -nr | nl |  head -n${1:-10}
}

h2d() {
	[ -z "$1" ] && echo "I can't dehex faic" && return
	hex=$(tr '[:lower:]' '[:upper:]' <<< $1)
	echo "obase=10; ibase=16; $hex" | bc
}

hex() {
	printf "$1" | od -t x1 -An | tr -d '\n '
}

monitor() {
	local _wh=$(tmux display -p '#{window_height}')
	local _ww=$(tmux display -p '#{window_width}')
	local _h=$(expr $_wh \* 45 / 100)

	[ "$_ww" -gt 200 ] && tmux split-window -h 'nvtop'

	tmux split-window -v
	tmux resize-pane -y $_h
	tmux send -t 1 'btop -p 0' ENTER
}

sprint() {
	local name="${1:-Tighearnán Carroll}"
	jira sprint list --current -q "Assignee in (\"$name\")"
}

éist() {
	local station=$1
	if [ -z "$station" ]; then
		station="fáilte"
	fi
	local url=https://radio.canstream.co.uk:9072/live.mp3
	case $station in
		"failte"|"fáilte")
			url=https://radio.canstream.co.uk:9072/live.mp3
			;;
		"life")
			url=https://streams.radiomast.io/71dd35ef-0299-44b5-a2dd-c35ca277d388
			;;
		"rí-rá"|"ri-ra"|"rr")
			url=https://uksoutha.streaming.broadcast.radio/ri-ra?1759322483879=
			;;
		"rnag")
			url=https://25283.live.streamtheworld.com/RTE_RAIDIO_NA_GAELTACHTA.mp3?tdsdk=rte
			;;
		*)
			echo "Níl an stáisiún sin agam ar an drochuair."
			return 1
	esac

	 mpv $url
}

eist() {
	éist $@
}


#command_not_found_handle
