[colors]
  draw_bold_text_with_bright_colors = false

  [colors.bright]
    black   = "#212121"
    blue    = "#61afef"
    cyan    = "#56b6c2"
    green   = "#53891c"
    magenta = "#bc93b6"
    red     = "#be354c"
    white   = "#f1f1f1"
    yellow  = "#ebd09c"

  [colors.normal]
    black   = "#212121"
    blue    = "#61afef"
    cyan    = "#56b6c2"
    green   = "#53891c"
    magenta = "#523c79"
    red     = "#be354c"
    white   = "#e0e0e0"
    yellow  = "#ebd09c"

  [colors.primary]
    background = "#d5d5d5"
    foreground = "#424242"

[font]
  size = 9.0

  [font.normal]
    style = "Regular"

[hints]
  alphabet = "jfkdls;ahgurieowpq"

[scrolling]
  history = 15000

[window]
  decorations   = "none"
  dynamic_title = false
  startup_mode  = "Windowed"
  title         = "Terminal"
